### ISSUE TITLE
Resource Exhausted Issue

### ISSUE THREAD

**Issue by MDVRP** [d-eremeev/ADM-VRP#2]
Hi!
I have been trying to train the model on larger sample size for larger graph size in an EC2 Instance with GPU containing 16 cores and VRAM 8GB . And I m facing the error of Resource Exhausted every time once the Baseline Model is Evaluated and then the Main model Training starts . What kind of system configuration is preferable to run this code ?

**Comment by alexeypustynnikov** [comment]
@MDVRP Hello! 
Thank you for your interest in our project!

The amount of used VRAM (considering fixed embedding_dim) depends on the following parameters: batch size (BATCH) and number of nodes in graph (GRAPH_SIZE).

You have to decrease batch size if you want to increase GRAPH_SIZE keeping VRAM 8 GB constraint.
I was able to run GRAPH_SIZE=50, BATCH=128 and GRAPH_SIZE=100, BATCH=32 on 8 GB VRAM GPU.
